# Generated by Django 6.0 on 2025-12-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_shelf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="source",
            field=models.URLField(unique=True),
        ),
    ]
