# Generated by Django 6.0.1 on 2026-03-07 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_image_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="position",
        ),
    ]
