# Generated by Django 6.0.1 on 2026-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_book_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookshelf",
            name="horizontal_position",
        ),
        migrations.RemoveField(
            model_name="bookshelf",
            name="vertical_position",
        ),
        migrations.AddField(
            model_name="book",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Position of the book within the shelf. From left to right.",
            ),
        ),
        migrations.AddField(
            model_name="bookcase",
            name="columns",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookcase",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="bookcase",
            name="rows",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookshelf",
            name="column",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookshelf",
            name="row",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
