# Generated by Django 6.0.1 on 2026-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_remove_bookshelf_horizontal_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcase",
            name="config",
        ),
        migrations.AddField(
            model_name="bookshelf",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
