# Generated by Django 6.0.6 on 2026-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_remove_bookcase_config_bookshelf_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookshelf",
            options={"ordering": ("row", "column")},
        ),
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="author",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
