# Generated by Django 6.0 on 2025-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="exc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apilog",
            name="status_code",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
