# Generated by Django 6.0 on 2025-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0002_apilog_exc_apilog_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="url",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apilog",
            name="service",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Openlibrary"), (2, "Moly"), (3, "Google Books")]
            ),
        ),
    ]
