# Generated by Django 6.0 on 2025-12-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0003_apilog_url_alter_apilog_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="content_type",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
