# Generated by Django 6.0 on 2025-12-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0004_apilog_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Openlibrary"),
                            (2, "Moly"),
                            (3, "Google Books"),
                            (4, "Image"),
                        ]
                    ),
                ),
                ("url", models.CharField(max_length=256)),
                ("method", models.CharField(max_length=8)),
                ("response", models.TextField()),
                ("content_type", models.CharField(max_length=64)),
                ("exc", models.TextField()),
                ("status_code", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="APILog",
        ),
    ]
