# Generated by Django 6.0.6 on 2026-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0005_responselog_delete_apilog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikidataCache",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "qid",
                        "claim",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qid", models.CharField(max_length=64)),
                ("claim", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="responselog",
            name="service",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Openlibrary"),
                    (2, "Moly"),
                    (3, "Google Books"),
                    (4, "Image"),
                    (5, "Wikidata"),
                ]
            ),
        ),
    ]
