# Generated by Django 6.0.6 on 2026-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0006_wikidatacache_alter_responselog_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikidatacache",
            name="pk",
        ),
        migrations.AddField(
            model_name="wikidatacache",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikidatacache",
            constraint=models.UniqueConstraint(
                fields=("qid", "claim"), name="unique_qid_claim"
            ),
        ),
    ]
